-- Add this to the bottom of the list in vehicles.lua, but above the end bracket for the list.

{ model = 'r820',               name = '2020 R8',                           brand = 'Audi',            price = 0,       category = 'AUDI',           type = 'automobile', shop = 'pdm' },
{ model = 'rs62',               name = '2020 RS6 Avant',                    brand = 'Audi',            price = 0,       category = 'AUDI',           type = 'automobile', shop = 'pdm' },
{ model = 'rs6',                name = '2016 RS6 C7',                       brand = 'Audi',            price = 0,       category = 'AUDI',           type = 'automobile', shop = 'pdm' },
{ model = 'sq72016',            name = '2016 SQ7',                          brand = 'Audi',            price = 0,       category = 'AUDI',           type = 'automobile', shop = 'pdm' },
{ model = 'Q820',               name = '2020 Q8',                           brand = 'Audi',            price = 0,       category = 'AUDI',           type = 'automobile', shop = 'pdm' },
{ model = '23rs7',              name = '2023 RS7',                          brand = 'Audi',            price = 0,       category = 'AUDI',           type = 'automobile', shop = 'pdm' },
{ model = 'mulca21',            name = '2021 Mulliner Bacalar',             brand = 'Bentley',         price = 0,       category = 'BENTLEY',        type = 'automobile', shop = 'pdm' },
{ model = 'f82',                name = '2015 F82 M4',                       brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = 'bmci',               name = '2018 M5 F90',                       brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = 'i8',                 name = '2015 I8',                           brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = 'bmwm8',              name = '2019 M8',                           brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = '750li',              name = '2016 750Li',                        brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = 'x5e53',              name = '2005 X5 E53',                       brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = 'bmwm4csl',           name = '2022 M4CSL',                        brand = 'BMW',             price = 0,       category = 'BMW',            type = 'automobile', shop = 'pdm' },
{ model = 'ctsv16',             name = '2016 CTS-V',                        brand = 'Cadillac',        price = 0,       category = 'CADILLAC',       type = 'automobile', shop = 'pdm' },
{ model = 'ct5v',               name = '2020 CT-V Sport',                   brand = 'Cadillac',        price = 0,       category = 'CADILLAC',       type = 'automobile', shop = 'pdm' },
{ model = 'ct5vbw22',           name = '2020 CT-V Blackwing',               brand = 'Cadillac',        price = 0,       category = 'CADILLAC',       type = 'automobile', shop = 'pdm' },
{ model = '211le',              name = '2022 ZL1-1LE',                      brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'checol17',           name = '2017 Colorado',                     brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'camaro90',           name = '1990 IROC-Z',                       brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'camrs17',            name = '2017 Camaro RS',                    brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = '13malibu',           name = '2013 Malibu',                       brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'czr1',               name = '2009 Corvette ZR1',                 brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'tahoe',              name = '2013 Tahoe',                        brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'c8',                 name = '2020 Corvette C8',                  brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'c7',                 name = '2014 Corvette C7 Stingray',         brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'subn',               name = '2016 Surburban',                    brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'silverado',          name = '2017 Silverado 1500 LTZ',           brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'silv20',             name = '2020 Silverado 1500 LT',            brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'caprice13',          name = '2013 Caprice',                      brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'caprice89w',         name = '1989 Caprice Wagon',                brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'chevropremtn',       name = '2019 Blazer Premier',               brand = 'Chevrolet',       price = 0,       category = 'CHEVROLET',      type = 'automobile', shop = 'pdm' },
{ model = 'pacifica',           name = '2020 Pacifica',                     brand = 'Chrysler',        price = 0,       category = 'CHRYLSER',       type = 'automobile', shop = 'pdm' },
{ model = 'chry300',            name = '2008 Chrysler',                     brand = 'Chrysler',        price = 0,       category = 'CHRYLSER',       type = 'automobile', shop = 'pdm' },
{ model = 'viper',              name = '2016 Viper SRT',                    brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = 'dl2016',             name = '2016 RAM 1500 Limited',             brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = 'chr20',              name = '2020 Hellcat Widebody',             brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = '16charger',          name = '2016 SRT Helllacat',                brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = 'demon',              name = '2018 SRT Demon',                    brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = 'ram16',              name = '2016 RAM Rebel',                    brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = 'ram2500',            name = '2015 RAM 2500',                     brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = '12charger',          name = '2012 Charger SRT',                  brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = '08magnumsrt',        name = '2008 Magnum SRT',                   brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = '3500flatbed',        name = '2010 RAM 3500 Flatbed',             brand = 'Dodge',           price = 0,       category = 'DODGE',          type = 'automobile', shop = 'pdm' },
{ model = 'bronco2021',         name = '2021 Bronco',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'raptor2017',         name = '2017 Raptor',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'focusrs',            name = '2017 Focus Rs',                     brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'mustang19',          name = '2019 Mustang GT',                   brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = '19Raptor',           name = '2019 Raptor',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = '19GT500',            name = '2019 Mustang Shelby GT500',         brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'wildtrak',           name = '2021 Bronco Wildtrak',              brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'everest',            name = '2018 Everest',                      brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'mache',              name = '2021 Mach-E',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'mach1',              name = '2021 Mach-1',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'f450plat',           name = '2021 F-450 Platinum',               brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'st',                 name = '2013 Focus ST',                     brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = '00f350d',            name = '2000 F-350 Super Duty',             brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'fescape',            name = '2012 Escape',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'crownvic2011',       name = '2011 Crown Victoria',               brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'expmax20',           name = '2020 Expedition',                   brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'taurus23',           name = '2023 Taurus',                       brand = 'Ford',            price = 0,       category = 'FORD',           type = 'automobile', shop = 'pdm' },
{ model = 'gmcyd',              name = '2015 Yukon Denali',                 brand = 'GMC',             price = 0,       category = 'GMC',            type = 'automobile', shop = 'pdm' },
{ model = '21sierra',           name = '2021 Sierra 1500',                  brand = 'GMC',             price = 0,       category = 'GMC',            type = 'automobile', shop = 'pdm' },
{ model = 'denalihd',           name = '2018 Sierra Denali 3500D',          brand = 'GMC',             price = 0,       category = 'GMC',            type = 'automobile', shop = 'pdm' },
{ model = 'terrain22',          name = '2022 Terrain AT4',                  brand = 'GMC',             price = 0,       category = 'GMC',            type = 'automobile', shop = 'pdm' },
{ model = 'fk8',                name = '2018 Civic Type-R',                 brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'nc1',                name = '2016 NSX',                          brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'fd2',                name = '2008 Civic Type-R',                 brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'ody18',              name = '2019 Odyssey Elite',                brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'cu2',                name = '2010 Accord',                       brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'citytrg',            name = '2016 City',                         brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'accord2017',         name = '2017 Accord',                       brand = 'Honda',           price = 0,       category = 'HONDA',          type = 'automobile', shop = 'pdm' },
{ model = 'veln',               name = '2018 Veloster N',                   brand = 'Hyundai',         price = 0,       category = 'HYUNDAI',        type = 'automobile', shop = 'pdm' },
{ model = 'sonata20',           name = '2020 Sonata Limited',               brand = 'Hyundai',         price = 0,       category = 'HYUNDAI',        type = 'automobile', shop = 'pdm' },
{ model = '16santafe',          name = '2016 Santa Fe',                     brand = 'Hyundai',         price = 0,       category = 'HYUNDAI',        type = 'automobile', shop = 'pdm' },
{ model = 'elantrang',          name = '2021 Elantra',                      brand = 'Hyundai',         price = 0,       category = 'HYUNDAI',        type = 'automobile', shop = 'pdm' },
{ model = '14grandeur',         name = '2014 Grandeur',                     brand = 'Hyundai',         price = 0,       category = 'HYUNDAI',        type = 'automobile', shop = 'pdm' },
{ model = 'srt8',               name = '2015 SRT-8',                        brand = 'Jeep',            price = 0,       category = 'JEEP',           type = 'automobile', shop = 'pdm' },
{ model = 'jeepg',              name = '2020 Gladiator Rubicon',            brand = 'Jeep',            price = 0,       category = 'JEEP',           type = 'automobile', shop = 'pdm' },
{ model = 'trhawk',             name = '2018 Grand Cherokee Trackhawk',     brand = 'Jeep',            price = 0,       category = 'JEEP',           type = 'automobile', shop = 'pdm' },
{ model = 'jeep2012',           name = '2012 Wrangler',                     brand = 'Jeep',            price = 0,       category = 'JEEP',           type = 'automobile', shop = 'pdm' },
{ model = 'wrangler22',         name = '2022 Wrangler Rubicon',             brand = 'Jeep',            price = 0,       category = 'JEEP',           type = 'automobile', shop = 'pdm' },
{ model = 'kiagt',              name = '2017 Stinger GT',                   brand = 'Kia',             price = 0,       category = 'KIA',            type = 'automobile', shop = 'pdm' },
{ model = 'optima',             name = '2014 Optima K5',                    brand = 'Kia',             price = 0,       category = 'KIA',            type = 'automobile', shop = 'pdm' },
{ model = '19sorento',          name = '2019 Sorento',                      brand = 'Kia',             price = 0,       category = 'KIA',            type = 'automobile', shop = 'pdm' },
{ model = 'kiasoul2',           name = '2020 Soul',                         brand = 'Kia',             price = 0,       category = 'KIA',            type = 'automobile', shop = 'pdm' },
{ model = 'sportage',           name = '2022 Sportage',                     brand = 'Kia',             price = 0,       category = 'KIA',            type = 'automobile', shop = 'pdm' },
{ model = '24telluridesxp',     name = '2024 Telluride SXP',                brand = 'Kia',             price = 0,       category = 'KIA',            type = 'automobile', shop = 'pdm' },
{ model = 'lex570',             name = '2016 LX570',                        brand = 'Lexus',           price = 0,       category = 'LEXUS',          type = 'automobile', shop = 'pdm' },
{ model = 'lc500',              name = '2018 LC500',                        brand = 'Lexus',           price = 0,       category = 'LEXUS',          type = 'automobile', shop = 'pdm' },
{ model = 'rx450h',             name = '2016 RX450h',                       brand = 'Lexus',           price = 0,       category = 'LEXUS',          type = 'automobile', shop = 'pdm' },
{ model = 'RC350S',             name = '2022 RC350',                        brand = 'Lexus',           price = 0,       category = 'LEXUS',          type = 'automobile', shop = 'pdm' },
{ model = 'xxxxx',              name = '2023 X-Class',                      brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 's500w222',           name = '2014 S500 AMG W222',                brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'c63w205',            name = '2017 C63S AMG',                     brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'XPERIA38',           name = '2019 G63 AMG',                      brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'e400',               name = '2019 E400 4-Matic',                 brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'v250',               name = '2019 V-Class',                      brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'gls63',              name = '2016 AMG GLS 63',                   brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'amggt',              name = '2016 AMG GT',                       brand = 'Mercedes-Benz',   price = 0,       category = 'MERCEDES-BENZ',  type = 'automobile', shop = 'pdm' },
{ model = 'evo10',              name = '2016 Lancer Evolution X',           brand = 'Mitsubushi',      price = 0,       category = 'MITSUBUSHI',     type = 'automobile', shop = 'pdm' },
{ model = 'rogue20',            name = '2020 Rogue Sport',                  brand = 'Nissan',          price = 0,       category = 'NISSAN',         type = 'automobile', shop = 'pdm' },
{ model = 'gtr',                name = '2017 GTR',                          brand = 'Nissan',          price = 0,       category = 'NISSAN',         type = 'automobile', shop = 'pdm' },
{ model = '370z',               name = '2016 370Z Nismo Z34',               brand = 'Nissan',          price = 0,       category = 'NISSAN',         type = 'automobile', shop = 'pdm' },
{ model = 'nissantitan17',      name = '2017 Titan Warrior',                brand = 'Nissan',          price = 0,       category = 'NISSAN',         type = 'automobile', shop = 'pdm' },
{ model = 'gtr50',              name = '2021 GT-R50',                       brand = 'Nissan',          price = 0,       category = 'NISSAN',         type = 'automobile', shop = 'pdm' },
{ model = 'qashqai16',          name = '2016 Qashqai',                      brand = 'Nissan',          price = 0,       category = 'NISSAN',         type = 'automobile', shop = 'pdm' },
{ model = 'tr22',               name = '2020 Roadster',                     brand = 'Tesla',           price = 0,       category = 'TESLA',          type = 'automobile', shop = 'pdm' },
{ model = 'tmodel',             name = '2018 Model 3',                      brand = 'Tesla',           price = 0,       category = 'TESLA',          type = 'automobile', shop = 'pdm' },
{ model = 'lc200',              name = '2016 Land Cruiser 200',             brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'camry55',            name = '2016 Camry',                        brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'camry18',            name = '2018 Camry XSE',                    brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'sclkuz',             name = '2020 Land Cruiser 200',             brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'supra19',            name = '2019 Supra GR',                     brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = '4runner',            name = '2020 4Runner',                      brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'hilux2019',          name = '2019 Hilux',                        brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'taco23',             name = '2023 Tacoma',                       brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'cruisersj',          name = '2020 LC200',                        brand = 'Toyota',          price = 0,       category = 'TOYOTA',         type = 'automobile', shop = 'pdm' },
{ model = 'R50',                name = '2008 Touareg R50',                  brand = 'Volkswagen',      price = 0,       category = 'VOLKSWAGEN',     type = 'automobile', shop = 'pdm' },
{ model = 'vwstance',           name = '2016 Passat',                       brand = 'Volkswagen',      price = 0,       category = 'VOLKSWAGEN',     type = 'automobile', shop = 'pdm' },
{ model = 'cox2013',            name = '2013 Beetle',                       brand = 'Volkswagen',      price = 0,       category = 'VOLKSWAGEN',     type = 'automobile', shop = 'pdm' },